config/routes.rb
C3web::Application.routes.draw do
  get "/", to: "index#index"

  get "login/", to: "login#index"

  get "login/in"

  get "login/out"

  get "login/change_password"
  get "login/passwords"

  resources :comments

  resources :posts

  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  attr_accessible :body, :user, :post, :post_id, :user_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    return forbidden unless isLoggedIn
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    return forbidden unless isCorrectUser @comment.user_id or isModerator
  end

  # POST /comments
  # POST /comments.json
  def create
    return forbidden unless isLoggedIn
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    return forbidden unless isCorrectUser @comment.user_id or isModerator

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    return forbidden unless isCorrectUser @comment.user_id or isModerator
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value=>session[:user_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :post_id, :value=>params[:post_reply] unless params[:post_reply].nil? %>
    <%= f.hidden_field :post_id, :value=>@comment.post_id unless @comment.post_id.nil? %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Body</th>
    <th>User</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
    <td><%= comment.user %></td>
    <td><%= comment.post %></td>
    <td><%= link_to 'Show', comment %></td>
    
<% if session[:user_id].to_i != 0 and (comment.user_id == session[:user_id] or User.find(session[:user_id]).moderator)%>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>User:</b>
  <%= link_to "#{@comment.user.name}", @comment.user %>
</p>

<p>
  <b>Post:</b>
  <%= link_to "#{@comment.post.title}", @comment.post %>
</p>


<% if session[:user_id].to_i != 0 and (@comment.user_id == session[:user_id] or User.find(session[:user_id]).moderator)%>
<%= link_to 'Edit', edit_comment_path(@comment) %> |
<% end %>